export const routes = {
  HOME: "/",
  MY_DATA: "my-data",
  PROFILE: "/profile",
  EVENTS: "/events",
  WORKOUT: "/workout",
  INPUT_DATA: "/workout/input-data",
  CREATE_TRAINING: "/workout/create-training",
  ADD_WORKOUT: "/workout/add-workout",
  CHOOSE_TRAINING: "/workout/choose-training",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  TRAIN: "/training",
  PAGE_NOT_FOUND_URL: "*",
};
